### PR TITLE
Fix statx constant fallback values, and fix with musl 1.2.5

### PR DESCRIPTION
**Pull request by alyssais**
Fixes https://github.com/ocaml-multicore/ocaml-uring/issues/112.

### CODE REVIEW

**Comment by alyssais** [comment]
Hmm, CI gets errors because some of them are unused.  I guess I should just remove those ones?

**Comment by alyssais** [comment]
Although… shouldn't they be used in `Attr`?

**Comment by talex5** [comment]
It's because you're generating some of them twice. Looking at _build/default/lib/uring/config.ml:
```
  module Attr = struct
    let dax = 0x200000
    let verity = 0x100000
    let mount_root = 0x2000
    let automount = 0x1000
    let encrypted = 0x800
    let nodump = 0x40                       <<<
    let append = 0x20
    let immutable = 0x10
    let compressed = 0x4
    let encrypted = 0x800
    let nodump = 0x40                      <<<
    let append = 0x20
    let immutable = 0x10
    let compressed = 0x4
  end
```

**Comment by alyssais** [comment]
Ah, of course.  Let's try this.

**Review by talex5 — APPROVED** [review]
Thanks, that's great!

**Pull request merged**
